
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/xiawucha?serverTimezone=UTC
      username: root
      password: 123456
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      use-key-prefix: false
      key-prefix: sms_
      cache-null-values: false
      time-to-live: 86400s
  mvc:
    servlet:
      load-on-startup: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml




